version: '3.9'

services:
  postgres:
    container_name: nest-app-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 2000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-app

volumes:
  postgres_data:

networks:
  nest-app: